document.write("<nav class=\"navbar navbar-default\">");
document.write("	<div class=\"container-fluid\">");
document.write("		<div class=\"navbar-header\">");
document.write("			<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">");
document.write("				<span class=\"icon-bar\"><\/span>");
document.write("				<span class=\"icon-bar\"><\/span>");
document.write("				<span class=\"icon-bar\"><\/span>");
document.write("			<\/button>");
document.write("			<a class=\"navbar-brand\" href=\"http:\/\/meetagee.github.io\"><span class=\"glyphicon glyphicon-console\"><\/span><b>LAM HOANG<\/b><\/a>");
document.write("		<\/div>");
document.write("		<div class=\"collapse navbar-collapse\" id=\"myNavbar\">");
document.write("			<ul class=\"nav navbar-nav navbar-right\">");
document.write("				<li><a href=\"http:\/\/meetagee.github.io\">ABOUT<\/a><\/li>");
document.write("				<li class=\"dropdown\">");
document.write("					<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">PROJECTS");
document.write("					<span class=\"caret\"><\/span><\/a>");
document.write("					<ul class=\"dropdown-menu\">");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/tetribass.html\">(TYPESCRIPT) TETRIBASS<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/rcCar.html\">(ARDUINO, C) RC CAR<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/nixie.html\">(C\/C++, ARDUINO) NIXIE CLOCK<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/nadeshiko.html\">(PYTHON) NADESHIKO - DISCORD BOT<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/osuKeypad.html\">(C\/C++, ARDUINO) OSU! KEYPAD<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/breaker.html\">(C\/C++) BREAKER<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/flynshoot.html\">(C\/C++) FLY N' SHOOT<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/aoc.html\">(C++) THE ART OF COMPRESSION<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/arc4.html\">(SYSTEMVERILOG) ARC4 DECRYPTION<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/vault.html\">(PYTHON\/HTML\/JS) MOBILE VAULT<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/techProjs\/graphs.html\">(JAVA) GRAPHS, NETWORKS, AND GAMES<\/a><\/li>");
document.write("					<\/ul>");
document.write("				<\/li>");
document.write("				<li class=\"dropdown\">");
document.write("					<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">EXPERIENCES");
document.write("	  <span class=\"caret\"><\/span><\/a>");
document.write("					<ul class=\"dropdown-menu\">");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/experience\/firmwareDevCoop.html\">FIRMWARE DEVELOPER COOP<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/experience\/iotIntern.html\">EMBEDDED SYSTEMS\/IOT DEPT INTERNSHIP<\/a><\/li>");
document.write("						<li><a href=\"https:\/\/meetagee.github.io\/experience\/translator.html\">MOVIE TRANSLATOR, CONTENT REVIEWER<\/a><\/li>");
document.write("					<\/ul>");
document.write("				<\/li>");
document.write("				<li><a href=\"https:\/\/meetagee.github.io\/interests\">INTERESTS<\/a><\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/nav>");
