document.write("<footer class=\"text-center\">");
document.write("	<a class=\"up-arrow\" href=\"#mainBody\" data-toggle=\"tooltip\" title=\"TO TOP\">");
document.write("		<span class=\"glyphicon glyphicon-chevron-up\"><\/span>");
document.write("	<\/a>");
document.write("	<br>");
document.write("	<br>");
document.write("	<p><b>Lam Hoang - 2022<\/b><\/p>");
document.write("	<p class=\"text-center\"><span class=\"glyphicon glyphicon-map-marker\"><\/span> Vancouver, BC, Canada<\/p>");
document.write("	<p class=\"text-center\"><span class=\"glyphicon glyphicon-envelope\"><\/span> Email: lamht1998@gmail.com<\/p>");
document.write("	<div class=\"row\" style=\"text-align:center\">");
document.write("		<a href=\"https:\/\/www.facebook.com\/lammm.hoang\" target=\"_blank\">");
document.write("			<button type=\"button\" class=\"btn btn-fb\"><i class=\"fa fa-facebook-f\"><\/i><\/button>");
document.write("		<\/a>");
document.write("		<a href=\"https:\/\/www.instagram.com\/hitag1\/\" target=\"_blank\">");
document.write("			<button type=\"button\" class=\"btn btn-fb\"><i class=\"fa fa-instagram\"><\/i><\/button>");
document.write("		<\/a>");
document.write("		<a href=\"https:\/\/github.com\/meetagee\/\" target=\"_blank\">");
document.write("			<button type=\"button\" class=\"btn btn-fb\"><i class=\"fa fa-github\"><\/i><\/button>");
document.write("		<\/a>");
document.write("		<a href=\"https:\/\/linkedin.com\/in\/\/tunglam-hoang\" target=\"_blank\">");
document.write("			<button type=\"button\" class=\"btn btn-fb\"><i class=\"fa fa-linkedin\"><\/i><\/button>");
document.write("		<\/a>");
document.write("	<\/div>");
document.write("<\/footer>");
