document.write("<meta charset=\"utf-8\">");
document.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.4.0\/css\/bootstrap.min.css\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css?family=Lato\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css?family=Montserrat\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("<script src=\"https:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/3.4.1\/jquery.min.js\"><\/script>");
document.write("<script src=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.4.0\/js\/bootstrap.min.js\"><\/script>");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/font-awesome\/4.7.0\/css\/font-awesome.min.css\">");
var isMainIdx = document.currentScript.getAttribute("isMainIdx") === "1";
document.write("<link rel=\"stylesheet\" type=\"text\/css\" href=\"" + (isMainIdx ? ".\/css\/style.css\">" : "..\/css\/style.css\">"));
document.write("<link rel=\"icon\" href=\"" + (isMainIdx ? ".\/media\/prog_lang_icon.png\">" : "..\/media\/prog_lang_icon.png\">"));
